nft-collector/main_app/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('allCollection/', views.allCollection, name='allCollection'),
    path('allCollection/<int:nft_id>/', views.nftDetails, name='detail'),
    path('allCollection/create/', views.NftCreate.as_view(), name='nft_create'),
    path('allCollection/<int:pk>/update/', views.nftUpdate.as_view(), name='nft_update'),
    path('allCollection/<int:pk>/delete/', views.nftDelete.as_view(), name='nft_delete'),
    path('allCollection/<int:nft_id>/add_rating/', views.add_rating, name='add_rating'),

    path('chain/', views.ChainList.as_view(), name='chain_index'),
    path('chain/<int:pk>/', views.ChainDetail.as_view(), name='chain_detail'),
    path('chain/create/', views.ChainCreate.as_view(), name='chain_create'),
    path('chain/<int:pk>/update/', views.ChainUpdate.as_view(), name='chain_update'),
    path('chain/<int:pk>/delete/', views.ChainDelete.as_view(), name='chain_delete'),

]

nft-collector/nftcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

nft-collector/main_app/models.py
from django.db import models

from django.urls import reverse

# Create your models here.


RATING= (
    ('1', '1 Star'),
    ('2', '2 Stars'),
    ('3', '3 Stars'),
    ('4', '4 Stars'),
    ('5', '5 Stars'),
)


class Chain(models.Model):
    name = models.CharField(max_length=50)
    number = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('chains_detail', kwargs={'pk': self.id})



class Nft(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    price = models.IntegerField()
    type = models.TextField()

    def get_absolute_url(self):
      return reverse('detail', kwargs={'nft_id': self.id})



class Rating(models.Model):
    date = models.DateField('date first observed')
    rating = models.CharField(
      max_length=1,
      choices=RATING,
      default=RATING[0][0]
    )
    
    nft = models.ForeignKey(Nft, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.get_rating_display()} on {self.date}'
    
    class Meta:
        ordering = ['-date']

nft-collector/main_app/forms.py
from django.forms import ModelForm
from .models import Rating




class RatingForm(ModelForm):
  class Meta:
    model = Rating
    fields = ['date', 'rating']

nft-collector/main_app/views.py
from django.shortcuts import render, redirect
# Create your views here.
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Nft, Chain

from .forms import RatingForm



def home(request):
    return render(request, 'nft/home.html')

def about(request):
    return render(request, 'about.html')

def allCollection(request):
    nfts = Nft.objects.all()
    return render(request, 'allCollection.html', {'nfts': nfts})

def nftDetails(request, nft_id):
    nfts = Nft.objects.get(id=nft_id)
    rating_form = RatingForm()

    return render(request, 'nft/detail.html', {'nfts': nfts, 'rating_form': rating_form})

class NftCreate(CreateView):
    model = Nft
    fields = '__all__' #['name', 'description', 'type', 'price'] <- telling django what keys on the model we want to genrate the form with.
    

class nftUpdate(UpdateView):
    model = Nft
    fields = '__all__'
        

class nftDelete(DeleteView):
    model = Nft
    success_url = '/allCollection/'


def add_rating(request, nft_id):
    form = RatingForm(request.POST)
    if form.is_valid():
        new_rating = form.save(commit=False)
        new_rating.nft_id = nft_id
        new_rating.save()
    return redirect('detail', nft_id = nft_id)    




class ChainList(ListView):
  model = Chain

class ChainDetail(DetailView):
  model = Chain

class ChainCreate(CreateView):
  model = Chain
  fields = '__all__'
  success_url = '/chain/'

class ChainUpdate(UpdateView):
  model = Chain
  fields = ['name', 'color']

class ChainDelete(DeleteView):
  model = Chain
  success_url = '/chain/'

nft-collector/main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nft Collection</title>
</head>

<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>About the Nft Collection Gallery</h1>
    <hr/>
    <p>The Nft Collector is the undisputed number one authority on Nfts</p>
    {% endblock %}
    <footer>All Rights Reserved, &copy; 2022 Nfts Collection Galery</footer>
</body>
</html>

nft-collector/main_app/templates/allCollection.html
{% extends 'base.html' %}
{% block content %}

<h1>NFT List</h1>

{% for nft in nfts %}
<a href="{% url 'detail' nft.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ nft.name }}</span>
      <p>Description: {{ nft.description }}</p>
      <p>Price: {{ nft.price }}</p>
      <p>Type: {{ nft.type }}</p>
    </div>
  </a>
  </div>
{% endfor %}

{% endblock %}

nft-collector/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Add NFT</title>
  <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
 <style>
body{
  background-color: #e8f6ff;


}
  a:link, a:visited {
    background-color: #a0423b;
    color: white;
    padding: 14px 25px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
  }
  
  a:hover, a:active {
    background-color: red;
  }


 </style>
</head>
<body>
  <header class="navbar-fixed">
  
    <table style="width:100%">
      <tr>
        <th><a href="/" class="left brand-logo">HOME</a></th>
        <th><a href="{% url 'chain_create' %}">Add Chain</a></th>
        <th><a href="{% url 'chain_index' %}">View All</a></th>
        <th><a href="/allCollection">All COLLECTION</a></th>
        <th><a href="{% url 'nft_create' %}">Add NFT</a></th>
        <th><a href="/about">ABOUT</a></th>
      </tr>
    
    </table>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 NFT Collector &nbsp;</div>
  </footer>
</body>
</html>

nft-collector/main_app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NFT COLLECTOR Collector</title>
</head>
<body>
     
      
{% extends 'base.html' %}
{%block content%}
    <center><h2>WELCOME TO NFT COLLECTION GALLERY 1</h2></center>
{%endblock%}
    
</body>
</html>

nft-collector/main_app/templates/main_app/chain_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Chain</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'chain_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

nft-collector/main_app/templates/main_app/chain_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Show Chain</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ chain.name }}</span>
        <p>Color: {{ chain.number }}</p>
      </div>
      <div class="card-action">
        <a class="btn" href="{% url 'chain_update' chain.id %}">Edit</a>
        <a class="btn" href="{% url 'chain_delete' chain.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

nft-collector/main_app/templates/main_app/chain_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add chain</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
	<!-- Django requires the following for security purposes -->
	{% csrf_token %}
	<table>
		<!-- Render the inputs inside of <tr>s & <td>s -->
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

nft-collector/main_app/templates/main_app/chain_list.html
{% extends 'base.html' %} {% block content %}

<center style="padding: 12px"><h2>Chain List</h2></center>
<div class="center">
  {% for chain in chain_list %}
  <a style="background-color: aliceblue;     padding: 0px" href="{% url 'chain_detail' chain.id %}">
    <div class="card">

          <h2>  Chain: {{ chain.name }}</h2>
          <h4>Chain No. {{ chain.number }}</h4>
    </div>
  </a>
  {% endfor %}
</div>

{% endblock %}

nft-collector/main_app/templates/main_app/nft_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Nft</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' nft.id %}">Cancel</a>
  </form>
{% endblock %}

nft-collector/main_app/templates/main_app/nft_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Display</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

nft-collector/main_app/templates/nft/detail.html
    {% extends 'base.html' %}
    {%block content%}

    <ul>
    <div class="card">
        <a href="{% url 'detail' nfts.id %}">
        <div class="card-content">
          <span class="card-title">{{ nfts.name }}</span>
          <p>Description: {{ nfts.description }}</p>
          <p>type: {{ nfts.type }}</p>
          <p>price: {{ nfts.price }}</p>
        </div>
      </a>
      </div>
    </ul>  
    <div class="card-action">
        <a class="btn" href="{% url 'nft_update' nfts.id %}">Edit</a>
        <a class="btn" href="{% url 'nft_delete' nfts.id %}">Delete</a>
      </div> 

<br>
<form action="{% url 'add_rating' nfts.id %}"method="post">
  {% csrf_token %}
  {{ rating_form.as_p }}
  <input type="submit" class="btn" value="Add Rating">
</form>
  
<br>

      <table class="striped">
        <thead>
          <tr><th>Date</th><th>Rating</th></tr>
        </thead>
        <tbody>
          {% for nft in nfts.rating_set.all %}
            <tr>
              <td>{{nft.date}}</td>
              <td>{{nft.get_meal_display}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>
  </div>

<script>

  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  })
  const selectEl = document.getElementById('id_rating');
  M.FormSelect.init(selectEl)
</script>

{%endblock%} 

nft-collector/main_app/templates/nft/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NFT COLLECTOR Collector</title>
</head>
<body>
     
      
{% extends 'base.html' %}
{%block content%}
    <center><h2>WELCOME TO NFT COLLECTION GALLERY</h2></center>
{%endblock%}
    
</body>
</html>

nft-collector/main_app/templates/nftDetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
</head>
<body>
     
      
{% extends 'base.html' %}
{%block content%}
    <center><h2>Details</h2></center>
{%endblock%}
    
</body>
</html>